package manifests

import (
	"context"
	"fmt"
	"path"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/openshift/api/features"
	mcfgv1alpha "github.com/openshift/api/machineconfiguration/v1alpha1"
	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/agent"
	"github.com/openshift/installer/pkg/asset/agent/workflow"
	"github.com/openshift/installer/pkg/asset/installconfig"
	"github.com/openshift/installer/pkg/rhcos"
	"github.com/openshift/installer/pkg/types"
)

var osImageStreamFileName = path.Join(openshiftManifestDir, "99_osimagestream.yaml")

// OSImageStream generates the OSImageStream manifest.
type OSImageStream struct {
	FileList []*asset.File
}

var _ asset.WritableAsset = (*OSImageStream)(nil)

// Name returns a human-friendly name for the asset.
func (*OSImageStream) Name() string {
	return "OS Image Stream"
}

// Dependencies returns all of the dependencies directly needed to generate
// the asset.
func (*OSImageStream) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the OSImageStream CRD.
func (f *OSImageStream) Generate(_ context.Context, dependencies asset.Parents) error {
	// Try IPI install config first
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	// Then try agent optional install config
	agentInstallConfig := &agent.OptionalInstallConfig{}
	agentWorkflow := &workflow.AgentWorkflow{}
	dependencies.Get(agentInstallConfig, agentWorkflow)

	var config *types.InstallConfig

	// Determine which install config to use
	if installConfig.Config != nil {
		// IPI workflow
		config = installConfig.Config
	} else if agentInstallConfig.Supplied && agentInstallConfig.Config != nil {
		// Agent workflow - only generate for install workflow, not add-nodes
		if agentWorkflow.Workflow != workflow.AgentWorkflowTypeInstall {
			return nil
		}
		config = agentInstallConfig.Config
	} else {
		// No install config available
		return nil
	}

	// If one of the following are true the OSImageStream CR is not generated
	// 1. The feature is not enabled
	// 2. The target is CentOS Stream CoreOS
	if !config.Enabled(features.FeatureGateOSStreams) || config.IsSCOS() {
		// FG disabled or not OCP
		return nil
	}

	// If no stream was set just report the default one for the current version
	stream := config.OSImageStream
	if stream == "" {
		stream = rhcos.DefaultOSImageStream
	}

	osImageStream := &mcfgv1alpha.OSImageStream{
		TypeMeta: metav1.TypeMeta{
			APIVersion: mcfgv1alpha.SchemeGroupVersion.String(),
			Kind:       "OSImageStream",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: "cluster",
		},
		Spec: &mcfgv1alpha.OSImageStreamSpec{
			DefaultStream: string(stream),
		},
	}

	osImageStreamData, err := yaml.Marshal(osImageStream)
	if err != nil {
		return fmt.Errorf("failed to create %s manifests from InstallConfig. Error: %w", f.Name(), err)
	}

	f.FileList = append(f.FileList, &asset.File{
		Filename: osImageStreamFileName,
		Data:     osImageStreamData,
	})
	return nil
}

// Files returns the files generated by the asset.
func (f *OSImageStream) Files() []*asset.File {
	return f.FileList
}

// Load loads the already-rendered files back from disk.
func (f *OSImageStream) Load(_ asset.FileFetcher) (bool, error) {
	return false, nil
}
